name: Cypress End-to-End Tests

on: 
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test
          record: false  # Set to true if you are recording your tests on the Cypress Dashboard
          config-file: cypress.config.js  # Specify your Cypress config file if not using the default one

      # Upload Mocha Awesome Report as an artifact
      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
            name: MOCHAWESOME HTML REPORT
            path: cypress/reports/.jsons # or path/to/artifact
