name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    
    # Run tests and generate Mocha Awesome report
    - name: Run Tests and Generate Report
      run: npm run test

    # List report files (for debugging)
    - name: List report files
      run: ls -R cypress/reports/.jsons

    # Upload Mocha Awesome Report as an artifact
    - name: Upload Mocha Awesome Report
      uses: actions/upload-artifact@v3
      with:
        name: mochawesome-report
        path: cypress\reports  # Use the correct directory where the final report is saved
