name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    # Run tests and generate Mocha Awesome report
    - name: Run Tests and Generate Report
      run: npm run test

    # Upload Mocha Awesome Report as an artifact
    - name: Upload Mocha Awesome Report
      uses: actions/upload-artifact@v3
      with:
        name: mochawesome-report
        path: reports # Adjust this path to where Mocha Awesome saves reports
